sudo: required
# language: generic
services:
  - docker

before_install:
  - docker build -t samuherek/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true samuherek/client-test npm test

after_success:
  - docker build -t samuherek/docker-multi-client ./client
  - docker build -t samuherek/docker-multi-nginx ./nginx
  - docker build -t samuherek/docker-multi-server ./server
  - docker build -t samuherek/docker-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push samuherek/docker-multi-client
  - docker push samuherek/docker-multi-nginx
  - docker push samuherek/docker-multi-server
  - docker push samuherek/docker-multi-worker
